exclude: scripts/
repos:
- repo: https://github.com/PyCQA/flake8
  rev: 3.8.3
  hooks:
  -   id: flake8
      additional_dependencies:
        - flake8-black
        - flake8-breakpoint
        - flake8-docstrings
        - pep8-naming
        - flake8-import-order
      args:
        - "-j8"
        - "--ignore=E203,E501,P103,D105,D401,I202,I101"
        - "--docstring-convention=numpy"
        - "--import-order-style=edited"
